### ISSUE TITLE
Please integrate the data from the DWD

### ISSUE THREAD

**Issue by wolfgang-58** [Gr3q/cinnamon-spices-applets#11]
Good morning,
First of all, thank you for the great applet. I think you also have a lot of friends in Germany and it would be great if you could integrate the data from the DWD (German Weather Service). There's a really good API there: https://brightsky.dev/
I would be happy if you could consider that soon.
Many greetings
THANKS!
wolfgang

**Comment by Gr3q** [comment]
has been completed for a while
